appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: mpy5iY39kxElczz27Yj6gMfkbLdKeVncgbEZSVNc6kaqAMD7c+KkXQqOt4mmrrYtJwKaVUk7TLEwUetHNj10C91fDamH6I04uZsGkQ/kCzNeEBGJYUMs5A7I2nr9FQygRSZsDj/ESIXKjeL3AOMeQ6NI4k0KGKE779NN03+kXBwZj0YruDc+EV8jzfOAgkiG4LeFHJO0vTCmUMWtDO61UppykZHqXdVuY2tQT3WWGy3DJzEIkOQeqBRiCuy1u/QoNRUfV5Rc5SinuGCqXzyS25HOUUkOx3bkjI5rJIcIvlKoiTTP+f8TrqUTl51FJv7Un+XorjTP6/MDhDGSXVFX81LzFPJ71Qamms/EiKjUu+HOlEOfZr+Jz7xlAhaQ9jwvoUXm7QZbV0pht/gFdk+GPIEJzWbouYjJ+On5NnYGwYvsbLBVcFGPJOarDcvSmnPeknVM4Px7eDtUi+LiwTPyZSaembniLyzt4ZNMLbUy56cmOUR33i9sw8Hnm8Y/TFFh6v+dBFqGoyDe6YSIVKmA4TfACq5BIL6/cJgL4PvpsKG7XxcDsOElFYd697hTKokPdk952VGm5Slj7I+1nQCwTGHvp/KhyziDI2bteKih/yOz/0m9kNg/DPl2RvOShxYGFJHRcNgpFiULT9p1zht8VVoTfHQOTHn17WREk8yGbFo=
conda_forge_output_validation: true
